### ISSUE TITLE
RatOS v2.0

### ISSUE THREAD

**Issue by miklschmidt** [Rat-OS/RatOS#37]
This release will not be backwards compatible with v1.x. https://github.com/Rat-OS/RatOS-configuration and https://github.com/Rat-OS/RatOS-configurator will get a v2.x branch which they'll be deployed from.

v1.x will continue to get moonraker/klipper compatibility fixes for 3 months from the release of v2.0, that should be enough time for users to migrate. From that point, v1.x will have reached end of life. Users can still stay on v1.x but will either have to mantain it themselves or stop updating.

**TODO:**
- [x] MCU wizard
- [x] SKR 3 EZ support
- [x] Resolve toolboard ADXL345 conflict with main control board.
- [x] Manta M4P support (https://github.com/Rat-OS/RatOS-configuration/pull/83 needs minor modifications)
- [x] Voron 2.4 support (https://github.com/Rat-OS/RatOS-configuration/pull/87)
- [x] printer.cfg install macro for Voron V2.4
- [x] Clean up stepper and driver configuration (get rid of backwards compat).
- [x] DFU instructions in board-definition.json for all toolboards
- [x] Ability to use sensorless and physical endstops simultaneously (PR needs minor work).
- [x] Move flashing of connected boards to configurator
- [x] Add configurator endpoints for registering klippy extras that should be symlinked
- [x] Handle klippy extension symlinking via configurator in install and update scripts
- [x] Disable IPv6 in avahi and nginx
- [x] MainsailOS merge
- [x] Docs on all the new macro variables.
- [x] Wiring diagrams for BTT EBB toolboards
- [x] Wiring diagrams for FLY SHT toolboards
- [ ] Clear up toolboards power wiring, show the plug
- [x] Wiring diagram for Manta M8P
- [x] Fan wiring diagram for Manta M8P
- [x] Wiring diagram for Manta M4P
- [x] Fan wiring diagram for Manta M4P
- [x] Wiring diagram for SKR 3
- [x] Wiring diagram for SKR 3 EZ
- [x] Wiring diagram for Mini E3 3.0 (WIP)
- [x] Docs rewrite, since MCU's are now flashed through the wizard
- [x] Docs for BTT EBB toolboards
- [x] Docs for FLY SHT toolboards
- [x] Docs for Manta M8P
- [x] Docs for Manta M4P
- [x] Docs for SKR 3 
- [x] Docs for SKR 3 EZ
- [x] Moonlight for notifications
- [x] Short documentation for Voron V0.1 similar to the existing printer docs
- [x] Short documentation for Voron V2.4 similar to the existing printer docs
- [x] #42
- [x] Docs on how to use stowable probes (basically an include and some position fiddling via a couple of variables).

**nice to haves** - *may be moved to 2.1*
- [x] Preinstalled and configured crowsnest and timelapse (comes with the MainsailOS merge)
- [ ] DFU instructions in board-definition.json for control boards
- [ ] Configurator support for selecting and sequentially flashing multiple control boards and multiple toolboards. Currently multiple boards can be flashed by jumping back and forth in the wizard, which is meh.
- [ ] Hevo support (https://github.com/Rat-OS/RatOS-configuration/pull/74).
